apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    {{- toYaml .Values.nexus.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.nexus.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8081
